services:
  grafana:
    image: grafana/grafana:10.4.3
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PLUGINS_ALLOW_LOCAL_MODE=true
    ports:
      - "3000:3000"
    volumes:
      - ./metrics:/var/lib/grafana/metrics:ro
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-storage:
